#!/bin/sh

# Mã màu ANSI
RED='\033[0;31m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # Reset màu

commit_msg=$(cat "$1")

if ! echo "$commit_msg" | grep -Eq "^(feat|fix|docs|style|refactor|test|chore): [a-zA-Z].*$"; then
  echo "${RED}❌ Commit message không hợp lệ!${NC}"
  echo "${BLUE}👉 Chuẩn commit message format: feat, fix, docs, style, refactor, test, chore${NC}"
  echo "${PURPLE}📌 Ví dụ: feat: add login${NC}"
  exit 1
fi

exit 0
